### ISSUE TITLE
When I trained model on liver tumor: stack expects each tensor to be equal size

### ISSUE THREAD

**Issue by hagersalehahmed** [uni-medical/SAM-Med3D#16]
When I trained model on liver tumor 

![image](https://github.com/uni-medical/SAM-Med3D/assets/56037425/d0caab78-10a1-4802-90a0-b0307651916d)

**Comment by blueyo0** [comment]
Hi, it seems to be a data-related issue.

Please provide more detailed information for the data you used and the trace log the code reported to help debug.

Thanks 👍

**Comment by hagersalehahmed** [comment]
The dataset

https://www.kaggle.com/code/luyen0/liver-segmentation-unet/input

ta/train/Liver_Tumor/tumor\imagesTr\volume_0096.nii.gz
 14%|████████████▌                                                                            | 9/64 [01:27<08:56,  9.76s/it]
Traceback (most recent call last):

           ^^^^^^^^^^^^^^^^^
  File "C:\Users\COMPUMARTS\anaconda3\envs\Lib\site-packages\torch\utils\data\dataloader.py", line 674, in _next_
data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\COMPUMARTS\anaconda3\envs\\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\COMPUMARTS\anaconda3\envs\Lib\site-packages\torch\utils\data\_utils\collate.py", line 265, in de
fault_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\COMPUMARTS\anaconda3\envs\Lib\site-packages\torch\utils\data\_utils\collate.py", line 142, in co
llate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\COMPUMARTS\anaconda3\envs\\Lib\site-packages\torch\utils\data\_utils\collate.py", line 142, in <l
istcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\COMPUMARTS\anaconda3\envs\Lib\site-packages\torch\utils\data\_utils\collate.py", line 119, in co
llate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\COMPUMARTS\anaconda3\envs\\Lib\site-packages\torch\utils\data\_utils\collate.py", line 162, in co
llate_tensor_fn
    return torch.stack(batch, 0, out=out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [1, 512, 512, 722] at entry 0 and [1, 128, 128, 128] at entr
y 1
