### ISSUE TITLE
请问为什么碰到了零除错误

### ISSUE THREAD

**Issue by 111678900** [uni-medical/SAM-Med3D#36]
Traceback (most recent call last):
  File "/content/SAM-Med3D/train.py", line 507, in <module>
    main()
  File "/content/SAM-Med3D/train.py", line 466, in main
    trainer.train()
  File "/content/SAM-Med3D/train.py", line 361, in train
    epoch_loss, epoch_iou, epoch_dice, pred_list = self.train_epoch(epoch, num_clicks)
  File "/content/SAM-Med3D/train.py", line 335, in train_epoch
    epoch_loss /= step
ZeroDivisionError: float division by zero请问这个到底为什么呀

**Comment by 111678900** [comment]
而且请问怎么测试呀

**Comment by blueyo0** [comment]
一般就是 step 为 0 所以除以0就出错了，建议debug查一下数据数量和路径。

测试的话目前只有validation.py 的 benchmarking 功能，教程在readme里，还没有在无标签数据直接test的功能。

对于自己的数据或者无标签数据的inference 参见https://github.com/uni-medical/SAM-Med3D/issues/22的说明，目前没写这个内容，后面会提供的。这个项目我只是业余在维护，这段时间一直有更高优先级的事挤在前面，我还发烧了，如有需要请稍微多等等吧 😿。

**Comment by quest-X** [comment]
> 而且请问怎么测试呀

我已经测试过了，效果不佳
