### ISSUE TITLE
ValueError:high<=0 && points=[]

### ISSUE THREAD

**Issue by Atoposiii** [uni-medical/SAM-Med3D#76]
Using my own data：

Traceback (most recent call last):
  File "/data/shaofengzou/PanSTEEL/SAM-Med3D/inference.py", line 457, in <module>
    seg_mask_list, points, labels = finetune_model_predict3D(
  File "/data/shaofengzou/PanSTEEL/SAM-Med3D/inference.py", line 254, in finetune_model_predict3D
    batch_points, batch_labels = click_methods[click_method](prev_masks.to(device), gt3D.to(device))
  File "/data/shaofengzou/PanSTEEL/SAM-Med3D/utils/click_method.py", line 201, in get_next_click3D_torch_ritm
    point = points[np.random.randint(len(points))]
  File "mtrand.pyx", line 765, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1247, in numpy.random._bounded_integers._rand_int64
ValueError: high <= 0

**Comment by blueyo0** [comment]
This error shows that your data is not in the expected format. Maybe you can check your data first. Here's the guideline: https://github.com/uni-medical/SAM-Med3D?tab=readme-ov-file#1-prepare-your-training-data-from-nnu-net-style-dataset
